---
title: "Models"
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
bibliography: '`r system.file("bibliography.bib", package = "pmrm")`'
vignette: >
  %\VignetteIndexEntry{Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

A progression model for repeated measures (PMRM) is a longitudinal continuous-time nonlinear model of a progressive disease.
The `pmrm` package implements PMRMs from @raket2022.
This vignette defines the models in the package.

# Common elements

This section defines the notation and assumptions common to all models in the package.

## Data

Let the scalar $y_{ij}$ be the continuous measure of disease severity of patient $i$ ($i = 1, \ldots, I$) at clinical visit $j$ (j = 1, \ldots, J).
For a progressive disease, we generally expect $y_{ij}$ to worsen from visit to visit.
The goal of treatment is typically to minimize the change in the observed outcome over time.

Some $y_{ij}$ values may be missing due to dropout or other intercurrent events.
We assume these outcomes are missing at random (MAR).
Except for the outcomes $y_{ij}$, all values in the data must be non-missing.

$t_{ij}$ is continuous time since the baseline visit of $j = 1$.
At baseline, we assume treatment has not been administered yet, so all study arms should have the same expected outcome if randomization is conducted properly.

The model may include optional covariates such as age and biomarker status.

## Likelihood

Let $y_i = (y_{i1}, \ldots, y_{iJ})$ be the vector of outcomes of patient $i$.
For each pair of different patients $i$ and $i^*$, we assume $y_i$ is independent of $y_{i^*}$ and $\text{Var}(y_i) = \text{Var}(y^*)$ .
For each $i$, define $\mu_i = E(y_i) = (\mu_{i1}, \ldots, \mu_{iJ})$ and $\Sigma = \text{Var}(y_i)$.

If there were no missing outcomes, we would assign a multivariate normal likelihood to each patient:

$$
\begin{aligned}
y_i \sim \text{MVN}(\mu_i, \Sigma)
\end{aligned}
$$

But to account for intercurrent events such as dropout, we assign patient-level marginal likelihoods that integrate over missing outcomes.
Let $Q_i$ be the $q \times I$ matrix such that $Q_i y_i$ is the chronologically ordered vector of all $q$ non-missing values of $y_i$.
Then the marginal likelihood for patient $i$ is:

$$
\begin{aligned}
Q_i y_i \sim \text{MVN}(Q_i \mu_i, Q_i \Sigma Q_i^T)
\end{aligned}
$$

The model is fit by maximizing the product of these independent marginal likelihoods over the latent parameters that define $\mu_i$ ($i = 1, \ldots, I$) and $\Sigma$.

## Variance

Recall that $\Sigma$ is defined as $\text{Var}(y_i)$ ($i = 1, \ldots, I$). 
We parameterize $\Sigma$ as follows:

$$
\begin{aligned}
\Sigma &= D \Lambda D
\end{aligned}
$$

$D$ is a $J \times J$ diagonal matrix with diagonal $\sigma = (\sigma_1, \ldots, \sigma_J)$ (the visit-specific standard deviation parameters).
To constrain $\sigma_j >= 0$ during maximum likelihood estimation, we define a latent parameter vector $\phi = (\phi_1, \ldots, \phi_J)$ such that $\phi_j = \log(\sigma_j)$ for $j = 1, \ldots, J$.

$\Lambda$ is the $J \times J$ correlation matrix among visits within a patient.
Define:

$$
\begin{aligned}
\Lambda &= L L^T
\end{aligned}
$$

$L$ is a lower triangular Cholesky factor of the correlation matrix $\Lambda$, and it is expressed in terms of a vector $\rho = (\rho_1, \ldots, \rho_{J(J - 1) / 2})$ of $\frac{J (J - 1)}{2}$ latent parameters.^[In R, `RTMB::unstructured(J)$corr(rho)` maps latent parameter vector `rho` to the $J \times J$ correlation matrix $L L^T$.]

The model estimates parameter vectors $\phi$ and $\rho$ with maximum likelihood.

## Expected value of the control group

Recall that $\mu_{ij}$ is the expected mean outcome of patient $i$ at visit $j$.
If patient $i$ is part of the control group, then we define: 

$$
\begin{aligned}
\mu_{ij} = f(t_{ij} | \xi, \alpha) + W_i \gamma - \langle \overline{W}_i, \gamma \rangle
\end{aligned}
$$

Each model expresses the expected outcomes differently, but all models reduce to the above equation for the control arm.

Above, $W_i$ is the $J \times V$ sparse model matrix of constant non-missing covariates from the data, $\overline{W}_i$ is $V$-length vector of the column means of $W_i$, and $\langle \overline{W}_i, \gamma \rangle$ is the inner product of $\overline{W}_i$ with model coefficient parameter vector $\gamma$.
We express the covariate adjustment as $W_i \gamma - \langle \overline{W}_i, \gamma \rangle$ for computational efficiency when dealing with sparse matrices.

The mean function $f(t_{ij} | \xi, \alpha)$ is the expected clinical outcome at time $t_{ij}$ of the control arm prior to covariate adjustment.
It is a spline with knots $\xi = (\xi_1, \ldots, \xi_S)$ and vertical anchor points $\alpha = (\alpha_1, \ldots, \alpha_S)$.^[In other words, $f(\xi_s | \xi, \alpha) = \alpha_s$ for $s = 1, \ldots, S$.]
The knots in $\xi$ are fixed and supplied by the user, and they are usually the scheduled visit times specified in the study protocol.^[However, both the discrete visit designations in the data and the spline knots in the model may need adjustment if many visits occurred off-schedule, as was the case for neurodegeneration studies during the COVID-19 pandemic.
(See @donohue2023).]

# The decline model




The decline model characterizes therapeutic benefit as a pointwise reduction in severity on the clinical outcome scale.
The expected amount of therapeutic benefit is assumed to be proportional to the amount of time elapsed since baseline.

## Definition

Define scalar $\beta_{k}$ for each study arm $k$ ($k = 1, \ldots, K$).
Let $k = 1$ denote the control arm, and let $b(i) \in \{1, \ldots, K\}$ indicate the study arm of patient $i$.
The proportional decline model is defined as:

$$
\begin{aligned}
y_{ij} &= \mu_{ij} + e_{ij}
\end{aligned}
$$

where:

$$
\begin{aligned}
\mu_{ij} &= (1 - \beta_{b(i)}) \left ( f(t_{ij} | \xi, \alpha) - f(0 | \xi, \alpha) \right ) + f(0 | \xi, \alpha) + W_{i}\gamma
\end{aligned}
$$

## Constraints

The model imposes a constraint so that the control arm ($k = 1$) is the reference arm:

$$
\begin{aligned}
\beta_k = \begin{cases}
0 & k = 1 \\
\theta_{k - 1} & k = 2, \ldots, K
\end{cases}
\end{aligned}
$$

The latent parameters $\theta_1, \dots, \theta_{K - 1}$ are estimated with maximum likelihood.

## Interpretation

$f(t_{ij} | \xi, \alpha) - f(0 | \xi, \alpha)$ quantifies the decline from baseline to visit $j$ in the health of patient $i$ due to the progression of the disease.
For $k > 1$, $1 - \beta_k$ is the ratio of the decline of arm $k$ to the decline of the control arm.
Thus, $\beta_k$ is the *reduction in decline* due to the therapy in study arm $k$.

## Baseline

At the baseline visit $j = 1$, we have $t_{i1} = 0$ for $i = 1, \ldots, I$, and thus:

$$
\begin{aligned}
y_{i1} &= f(0 | \xi, \alpha) + W_{i}\gamma + e_{ij}
\end{aligned}
$$

This property constrains the expected outcomes of all study arms to be equal at baseline.
This is known as constrained longitudinal data analysis (cLDA) [@wang2022].


# Non-proportional decline model

The non-proportional decline model is the same as its proportional variant, except the treatment effect parameters are time-specific.

## Definition

Let $\beta_{kj}$ be the pointwise therapeutic benefit of treatement $k$ relative to control ($k = 1$) at visit $j$.
We express the fitted values $\mu_{ij}$ in terms of $\beta_{b(i)j}$:

$$
\begin{aligned}
\mu_{ij} &= (1 - \beta_{b(i)k}) \left ( f(t_{ij} | \xi, \alpha) - f(0 | \xi, \alpha) \right ) + f(0 | \xi, \alpha) + W_{i}\gamma
\end{aligned}
$$

## Constraints

For identifiability, we set the control arm ($k = 1$) and baseline visit ($j = 1$) as reference levels.
We do this by expressing the treatment effects $\beta_{kj}$ in terms of latent scalar parameters $\theta_{(k - 1)(j - 1)}$:

$$
\begin{aligned}
\beta_{kj} = \begin{cases}
0 & k = 1 \text{ or } j = 1 \\
\theta_{(k-1)(j-1)} & k \in \{2, \ldots, K\} \text{ and } j \in \{2, \ldots, J\}
\end{cases}
\end{aligned}
$$

The model estimates the latent parameters $\theta_{11}, \ldots, \theta_{(K - 1)(J - 1)}$ with maximum likelihood.



# Non-proportional slowing model

The non-proportional slowing model characterizes the benefit from treatment as a slowing in the disease progression trajectory.
Whereas the proportional decline model expresses treatment effects on the clinical outcome scale, the non-proportional slowing model expresses treatment effects on the continuous time scale.
As explained in the "Interpretation" section, this model assumes each treatment does not noticeably accelerate the rate of disease progression.

## Definition

Define scalar $\beta_{kj}$ for each study arm $k$ ($k = 1, \ldots, K$) and visit $j$ ($j = 1, \ldots, J$).
Let $k = 1$ denote the control arm, and let $b(i) \in \{1, \ldots, K\}$ indicate the study arm of patient $i$.
Define $u_{ij}$ as follows:

$$
\begin{aligned}
u_{ij} = (1 - \beta_{b(i)j}) t_{ij}
\end{aligned}
$$

The non-proportional slowing model is defined as:

$$
\begin{aligned}
y_{ij} &= \mu_{ij} + e_{ij}
\end{aligned}
$$

where:

$$
\begin{aligned}
\mu_{ij} &= f \left ( u_{ij} | \xi, \alpha \right) + W_{i}\gamma
\end{aligned}
$$

## Constraints

The model imposes constraints on the $\beta_{kj}$ parameters.
The purpose is to preserve identifiability at baseline, with the control arm as the reference arm.
We impose these constraints by expressing each non-constant $\beta_{kj}$ in terms of a latent scalar parameter $\theta_{(k-1)(j-1)}$:

$$
\begin{aligned}
\beta_{kj} = \begin{cases}
0 & k = 1 \text{ or } j = 1 \\
\theta_{(k-1)(j-1)} & k \in \{2, \ldots, K\} \text{ and } j \in \{2, \ldots, J\}
\end{cases}
\end{aligned}
$$

The model estimates the latent parameters $\theta_{11}, \ldots, \theta_{(K - 1)(J - 1)}$ with maximum likelihood.

## Interpretation

$\beta_{kj}$ is a span of time: it is the relative slowing of the disease progression trajectory.
In other words, $\beta_{kj}$ is the expected amount of time (or quality time) that patients gain in their lives due to therapy $k$.

$u_{ij}$ is the *effective* time along the disease progression trajectory of patient $i$ at visit $j$.
If the active therapy of patient $i$ is efficacious, then the patient will experience disease progression more slowly than they would have in the control group, and the values of $u_{ij}$ will be less than the corresponding values of $t_{ij}$. In other words, the treatment effect is a time shift.

If the treatment slows disease, then the fitted response $f \left ( u_{ij} | \xi, \alpha \right)$ is an interpolation of the control arm at an earlier time point.
But if the treatment *accelerates* disease, then the fitted response is a significant extrapolation, and the model will not fit well.
Thus, the non-proportional slowing model assumes that no treatment is noticeably worse than control.

## Baseline

At the baseline visit $j = 1$, we have $t_{i1} = 0$ for $i = 1, \ldots, I$, and thus $u_{i1} = 0$.
The outcome for patient $i$ becomes:

$$
\begin{aligned}
y_{ij} &= f \left (0 | \xi, \alpha \right) + W_{i}\gamma + e_{ij}
\end{aligned}
$$

As with the proportional decline model, this property constrains the expected outcomes of all study arms to be equal at baseline.
In other words, the model uses constrained longitudinal data analysis (cLDA) [@wang2022].

## Prediction

The modeling functions in `pmrm` report the estimate and standard error of each parameter, along wit the mean outcome for each study arm at each of a set of user-defined time points.
The covariate adjustment term $W_i \gamma$ is omitted.

The `RTMB` package facilitates predictions using the `ADVECTOR()` function, which leverages the gradient and the delta method to calculate an estimate and standard error of user-defined quantities.
This happens during the model-fitting, so the `predict()` method cannot accept new ad hoc data.

# References
